# This workflow will setup python 3.10, install the dependencies in requirements.txt and run the tests in tests/test.py
# It will then also create a coverage report

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-run-python-tests:
    uses: Mews/.github/workflows/run-python-tests.yaml@main
    with:
      python_versions: '["3.10", "3.11", "3.12"]'
      os_list: '["ubuntu-latest", "windows-latest"]'